class grad_linearSD {
    class linearSD {
        class activateFortifications {};
        class activeSectorBeingCaptured {};
        class addChatCommands {};
        class addFortifications {};
        class addRespawnPosition {};
        class addTeleportAction {};
        class addVehicles {};
        class createSector {};
        class dynamicText {};
        class endRound {};
        class isLastSector {};
        class movePlayerToRespawnPos {};
        class moveRespawnPositions {};
        class onPlayerKilled {};
        class onSectorCaptured {};
        class playzoneCleanup {};
        class respawnPlayer {};
        class setActiveSectors {};
        class setLastRound {};
        class setTimeAndDate {};
        class spawnSectorVehicles {};
        class startEliminationCheck {};
        class startLinearSD {};
        class startNewRound {};
        class startTimeout {};
    };
};
